### ISSUE TITLE
"FSI.collectAndRun"がうまく動作しません。。。

### ISSUE THREAD

**Issue by callmekohei** [persimmon-projects/Persimmon.Script#5]
前回のバージョンの時は動いてたのですが、今回のバージョンだとエラーが出ます。

`vim`の`vim-quickrun`というプラグイン上でエラーがでるので

`vim-quickrun`の不具合のような気もしますが、

```
前回のバージョンだと動いた

Script.collectAndRunだと動作する
```

という２点で`Persimmon.Script`（というか`Runnner`のほう？）の不具合の可能性もあるような気がしました。

詳細は下記に書きましたので、お手すきの時に調べていただけると嬉しいです。

https://github.com/thinca/vim-quickrun/issues/161

**Comment by callmekohei** [comment]
# 原因わかりました！

### context.Name の取り扱い

| 実行方法        | context.Name           |
| ------------- |:-------------:|
| $ fsharpi "./abc.fsx"      | FSI_0001 |
| $ echo '#load "./abc.fsx"'  \| fsharpi --readline-      | "Abc"      |

`fsharpi`コマンドを実行したときと、`#load`コマンドを実行したときでデーターを読む場所が変わってます。プルリクをだしますので対応をお願います。(^_^)/

**Comment by callmekohei** [comment]
# 質問が・・

とりあえず`Assembly.GetExecutingAssembly().GetTypes()`を

`Persimmon.Script`に渡す形で実験してみました。

`FSI`モジュールのコードを書き換えたのですが、最新の結果がかえってきません。

おそらく`Persimmon`本体のコードに起因してると思うのですが・・・

追いきれませんでした。すいません。

申し訳ないですが`Persimmon`本体のコードを調べていただけないでしょうか？

```fsharp
module FSI =

  let run (namespaceIndex:string option) (f: ScriptContext -> #seq<#TestMetadata>) (ctx: ScriptContext) =

    ctx.Run(
      f
      >> Seq.choose (function
      | Context context ->
        namespaceIndex
        |> Option.bind (fun name ->
          let m = Regex.Match(name, "FSI_([0-9]+)")
          if m.Success then
            match Int32.TryParse(m.Groups.[1].Value) with
            | true, n -> 
                Some(n, context :> TestMetadata)
            | false, _ -> None
          else None
        )
      | _ -> None
      )
      >> Seq.maxBy fst
      >> snd
      >> Seq.singleton
    )

  let collectAndRun (ary:System.Type[]) f (ctx: ScriptContext) =
    
    let n = 
        ary
        |> Array.last
        |> fun x -> x.Namespace
        |> fun s -> s.ToString()
        |> fun s -> Some s

    ctx
    |> run n ( f >> Seq.singleton >> Runner.TestCollector.collectRootTestObjects)
```
実行コード
```fsharp
/// require Persimmon libraries and open modules.
#r "../jikkenjikken/packages/Persimmon/lib/net45/Persimmon.dll"
#r "../jikkenjikken/packages/Persimmon.Runner/lib/net40/Persimmon.Runner.dll"
#r "/Users/callmekohei/tmp/Persimmon.Script/src/Persimmon.Script/bin/Debug/netstandard1.6/Persimmon.Script.dll"

open Persimmon
open UseTestNameByReflection
open System.Reflection

/// write your test code here.
let ``a unit test`` = test {
  do! assertEquals 1 3
}

/// print out test report
new ScriptContext()
|> FSI.collectAndRun (Assembly.GetExecutingAssembly().GetTypes()) ( fun _ -> Assembly.GetExecutingAssembly() )
```

**Comment by pocketberserker** [comment]
Persimmon本体の挙動が意図せず変わっていたために発生した問題でした。
この問題を修正したPersimmonを依存関係に含んでいる Persimmon.Script 3.0.1 をリリースしたので試してみてください。

**Comment by callmekohei** [comment]
試してみました！

完璧に動作します！

ばっちりです！

早速の対応ありがとうございます！

(^_^)/

**Comment by callmekohei** [comment]
![untitled](https://user-images.githubusercontent.com/17691683/33111853-807439d0-cf93-11e7-9c35-64007deae6b0.gif)
